experiment_name: evflow_original
test_output_dir: results/evflow_original
use_compile: false
task: flow

module:
  loss:
    l1_weight: 1.0
    optical_flow_source: raft_large
    raft_num_flow_updates: 12

  normalize_voxels: false
  model:
    target: model.model.EVFlowNet
    params:
      unet_kwargs:
        num_bins: 5
        base_num_channels: 32
        num_encoders: 4
        num_residual_blocks: 2
        num_output_channels: 2
        skip_type: concat
        norm: null
        use_upsample_conv: true
        kernel_size: 3
        channel_multiplier: 2
              
test_stage:
  test_batch_size: 1
  test_num_workers: 16
  test:
    - data_file: config/evaid_test.txt
      class_name: data.testh5.TestH5Dataset
      dataset_name: evaid
      num_bins: 5
      sequence_length: 10
      interpolate_bins: true
      output_additional_frame: true
      image_range: 1
      max_samples: 2
    - data_file: config/ijrr_test.txt
      class_name: data.testh5.TestH5Dataset
      dataset_name: ijrr
      num_bins: 5
      sequence_length: 80
      interpolate_bins: true
      output_additional_frame: true
      image_range: 1
      max_samples: 2
    - data_file: config/hqf_test.txt
      class_name: data.testh5.TestH5Dataset
      dataset_name: hqf
      num_bins: 5
      sequence_length: 80
      interpolate_bins: true
      output_additional_frame: true
      image_range: 1
      max_samples: 2
    - data_file: config/mvsec_test_flow.txt
      class_name: data.testh5.TestH5FlowDataset
      dataset_name: mvsec
      num_bins: 5
      sequence_length: 80
      interpolate_bins: true
      output_additional_frame: true
      image_range: 1