experiment_name: nernet_original
test_output_dir: results/nernet_original

module:
  is_nernet: true
  loss:
    lpips_weight: 1.0
    lpips_type: alex
    l2_weight: 0
    l1_weight: 0
    ssim_weight: 0
    temporal_consistency_weight: 1.0

  normalize_voxels: false
  model:
    target: model.nernet_model.RepresentationRecurrent
    params:
      unet_kwargs:
        num_bins: 5
        skip_type: "sum"
        recurrent_network: "NIAM_STcell_GCB"
        recurrent_block_type: ""
        num_encoders: 3
        base_num_channels: 32
        num_residual_blocks: 2
        use_upsample_conv: true
        norm: ""
        crop_size: 224
        mlp_layers:
          - 1
          - 50
          - 50
          - 50
          - 1
        use_cnn_representation: true
        normalize: false
        combine_voxel: false
        RepCNN_kernel_size: 3
        RepCNN_padding: 1
        RepCNN_channel: 64
        RepCNN_num_layers: 1
        num_output_channels: 1

test_stage:
  test_batch_size: 1
  test_num_workers: 0
  test:
    - data_file: config/evaid_test.txt
      class_name: data.testh5.TestH5EventDataset
      dataset_name: evaid
      num_bins: 5
      sequence_length: 80
      interpolate_bins: true
    - data_file: config/ijrr_test.txt
      class_name: data.testh5.TestH5EventDataset
      dataset_name: ijrr
      num_bins: 5
      sequence_length: 80
      interpolate_bins: true
    - data_file: config/hqf_test.txt
      class_name: data.testh5.TestH5EventDataset
      dataset_name: hqf
      num_bins: 5
      sequence_length: 80
      interpolate_bins: true
    - data_file: config/mvsec_test.txt
      class_name: data.testh5.TestH5EventDataset
      dataset_name: mvsec
      num_bins: 5
      sequence_length: 80
      interpolate_bins: true