experiment_name: e2vid++_original
test_output_dir: results/e2vid++_original

module:
  lr_scheduler:
    target: torch.optim.lr_scheduler.ReduceLROnPlateau
    params:
      mode: 'min'
      factor: 0.5  # 当触发条件满足时，学习率将乘以此因子
      patience: 10  # 在触发学习率下降之前，允许的连续无改进的epoch数

  loss:
    lpips_weight: 1.0
    lpips_type: alex
    l2_weight: 0
    l1_weight: 0
    ssim_weight: 0
    temporal_consistency_weight: 1.0

  normalize_voxels: false
  model:
    target: model.model.FlowNet
    params:
      unet_kwargs:
        num_bins: 5
        skip_type: sum
        recurrent_block_type: convlstm
        num_encoders: 3
        base_num_channels: 32
        num_residual_blocks: 2
        use_upsample_conv: true
        norm: none
        num_output_channels: 3
          
test_stage:
  test_num_workers: 4
  test:
    - data_file: config/evaid_test.txt
      class_name: data.testh5.TestH5Dataset
      dataset_name: evaid
      num_bins: 5
      sequence_length: 80
      interpolate_bins: true
    - data_file: config/ijrr_test.txt
      class_name: data.testh5.TestH5Dataset
      dataset_name: ijrr
      num_bins: 5
      sequence_length: 80
      interpolate_bins: true
    - data_file: config/hqf_test.txt
      class_name: data.testh5.TestH5Dataset
      dataset_name: hqf
      num_bins: 5
      sequence_length: 80
      interpolate_bins: true
    - data_file: config/mvsec_test.txt
      class_name: data.testh5.TestH5Dataset
      dataset_name: mvsec
      num_bins: 5
      sequence_length: 80
      interpolate_bins: true